version: '3.1'
services:
  influx_nginx:
    restart: always
    image: nginx
    container_name: influx_nginx
    privileged: false
    pid: "host"
    cpus: 1
    mem_limit: 1024m
    ports:
      - 8080:8080
    volumes:
      - /etc/hosts:/etc/hosts
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - $PWD/influx_nginx.conf:/etc/nginx/nginx.conf


